### ISSUE TITLE
In scanning.py, how much screening for malformed events?

### ISSUE THREAD

**Issue by MaineTim** [Marzona/rig-remote#44]
Question on  this code in _process_queue:

```
            try:
                name, value = task.scanq.get_event_update()
            except NoneType:
                name = value = None
            key = str(name.split("_", 1)[1])
```

The only way the get_event_update() is called is if task.scanq.update_queued() is True, so it should never return None. If it does, shouldn't we raise some kind of exception to isolate how the queue got corrupted, rather than passing on problem to the code below?

As far as the rest of the code in the method, it assumes well-formed event updates, because the only thing that generates them is tkinter events from specific widgets. Should the rest of the processing code be prepared to handle mal-formed events if in theory they shouldn't be possible? It's easily doable, but I ask the question to get a sense of how much internal data testing we think is necessary in situations where the data in and out of a given method is supposed to be controlled already.

**Comment by Marzona** [comment]
I think that there is no complete answer.

short proposal IMHO is "if we are fine assuming that only tkinter will generate the events we may skip the check. if it's easy cut an issue and when there is nothing with higher priority we will address it, just record the intent."

To be strict, every method should "control the borders" or should assume that everything is always fine and properly handle the exceptions .

Ideally, for data that is generated from "already tested code" we may safely assume... we should not test every library/module we use..tkinter should have his own tests for this.

silly scenario: what if a tkinker release introduces some changes and because of that we got the queues corrupted? (assume that rig-remote is a more complex tool than what it is now) We may go crazy finding where the problem is.. if we try/except as soon as the data is inserted in the queue we may be able to spot out the problem close to its first appearance.

Moreover, now the only thing that generates them is tkinter we can assume that this will stay true for ever, but...

The balance may be on the lines of check the changelog of tkinter and "support" only specific versions, or release updates in rig-remote accordingly.
Another "balance" may be on the lines of "given the usecase of rig-remote we accept the risk of having the queues polluted and we will update the code when it will happen, assuming that the tkinter events will not change in the upcoming releases".

Another reply:"how much internal data testing we think is necessary " -> as much as we think is appropriate depending on the "customer impact/side effects" of a potential failure.

make sense?

**Comment by MaineTim** [comment]
Okay, thanks. I know it seems like a pedantic question, but just trying to get a feel for your view for coding going forward. I added some tests in commit f7a3a08, which would let a bad update drop and just notify us of the occurrence. In this case, it's probably overkill, but not expensive overkill, and if it did fail somehow, it sure would be interesting to know..

**Comment by Marzona** [comment]
pedantic question: it is not. feel free to ask.
